export const GET_ALL_STUDENT_REQUEST = 'GET_ALL_STUDENT_REQUEST';
export const GET_ALL_STUDENT_SUCCESS = 'GET_ALL_STUDENT_SUCCESS';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const TOGGLE_NAME = 'TOGGLE_NAME';




